### ISSUE TITLE
Update faker

### ISSUE THREAD

**Issue by mcmcgrath13** [brown-ccv/task-registry-faker#17]
Update faker to use this specification

```yml
taskName: [String, required]
links:
  deployment: [String::URL, optional]
  sourceCode: [String::URL, required]
  publication: [String::URL, optional]

framework:
  library: [Array, optional]
    - [String]
  language: [Array, optional]
    - [String]

lab:
  name: [String, required]
  institution: [String, required]
  principalInvestigator: [String, optional]
  developers: [Array, optional]
    - [String]
    - [String]
  website: [String::URL, optional]

platform:
  desktop:
    windows: [Boolean, optional, default=false]
    linux: [Boolean, optional, default=false]
    mac: [Boolean, optional, default=false]
  mobile:
    ios: [Boolean, optional, default=false]
    android: [Boolean, optional, default=false]
    windows: [Boolean, optional, default=false]

features:
  electron: [Boolean, optional, default=false]
  browser: [Boolean, optional, default=false]
  docker: [Boolean, optional, default=false]
  eegTrigger: [Boolean, optional, default=false]
  mturk: [Boolean, optional, default=false]

tags: [Array, optional]
  - [String]
```
