### ISSUE TITLE
register msit task

### ISSUE THREAD

**Issue by fernandogelin** [brown-ccv/task-registry-faker#33]
Instructions: Fill in the below yml template as per the specification in the comments.
```yml
taskName: MSIT Task
links: 
  sourceCode: https://github.com/brown-ccv/task-msit
framework:
  library: # [Array::String, optional]
    - jsPsych 
    - Electron
  language: # [Array::String, optional]
    - javascript
lab:
  name: Borton Lab
  institution: Brown University
  principalInvestigator: David Borton, PhD
  developers: 
    - Evan DVR
    - Fernando Gelin
  website: https://borton.engin.brown.edu
platform: # [Boolean, optional]
  desktop:
    windows: true
    linux: true
    mac: true
  mobile:
    ios: false
    android: false
features: # [Boolean, optional]
  electron: true
  browser: false
  docker: false
  eegTrigger: true
  mturk: true
tags: # [Array::String, optional]
  - TAG_1
  - TAG_2
  - TAG_3
  - TAG_4
```
