### ISSUE TITLE
my real task

### ISSUE THREAD

**Issue by mcmcgrath13** [brown-ccv/task-registry-faker#37]
**Instructions**
Fill in the below yml template as per the specification in the comments.
```yml
taskName: real task # [String, required]
links: 
  deployment: https://realtask.com # [String::URL, optional]
  sourceCode: https://github.com/real/task # [String::URL, required]
  publication: https://real.com # [String::URL, optional]
framework:
  library: # [Array::String, optional]
    - nano 
    - micro
    - mini
  language: # [Array::String, optional]
lab:
  name: real lab# [String, required]
  institution: real u# [String, required]
  principalInvestigator: # [String, optional]
  developers: # [Array::String, optional]
  website: https://example.com
platform: # [Boolean, optional]
  desktop:
    windows: false
    linux: true
    mac: false
  mobile:
    ios: false
    android: false
features: # [Boolean, optional]
  electron: false
  browser: false
  docker: true
  eegTrigger: false
  mturk: false
tags: # [Array::String, optional]
  - needs examples
```
