### ISSUE TITLE
realest task

### ISSUE THREAD

**Issue by mcmcgrath13** [brown-ccv/task-registry-faker#38]
**Instructions**
Fill in the below yml template as per the specification in the comments.
```yml
taskName: realest # [String, required]
links: 
  deployment: https://realest.com # [String::URL, optional]
  sourceCode: https://github.com/realest/task # [String::URL, required]
  publication: https://realest.com # [String::URL, optional]
framework:
  library: # [Array::String, optional]
    - realest 
  language: # [Array::String, optional]
    - realest
    - LANGUAGE_2
lab:
  name: realest# [String, required]
  institution: realest# [String, required]
  principalInvestigator: # [String, optional]
  developers: # [Array::String, optional]
    - realest
  website: https://realest.com
platform: # [Boolean, optional]
  desktop:
    windows: false
    linux: false
    mac: false
  mobile:
    ios: false
    android: false
features: # [Boolean, optional]
  electron: false
  browser: true
  docker: false
  eegTrigger: false
  mturk: false
tags: # [Array::String, optional]
  - realest
```
